- name: Bonnie Glaser
  category: ["US", "Think Tank"]
  enabled: true

- name: Ryan Hass
  category: ["US", "Think Tank"]
  enabled: true

- name: Kori Schake
  category: ["US", "Defense"]
  enabled: true

- name: Oriana Skylar Mastro
  category: ["US", "China", "Defense"]
  enabled: true

- name: Zack Cooper
  category: ["US", "Defense"]
  enabled: true

- name: 胡錫進
  category: ["China", "Media"]
  enabled: true

- name: 金燦榮
  category: ["China", "Scholar"]
  enabled: true